parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_DRIVER): 'pdo_mysql'
    env(DATABASE_URL): ''

doctrine:
    dbal:
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Bolt:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/bolt/core/src/Entity'
                prefix: 'Bolt\Entity'
                alias: Bolt
        dql:
            string_functions:
                JSON_EXTRACT: Bolt\Doctrine\Functions\JsonExtract
                JSON_GET_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                JSON_UNQUOTE: Bolt\Doctrine\Functions\JsonUnquote
                CAST: Bolt\Doctrine\Query\Cast
            numeric_functions:
                RAND: Bolt\Doctrine\Functions\Rand

