name: Continuous Integration

on: [pull_request]

jobs:

  test-install-with-composer-and-sqlite:
    name: Install Bolt project with Composer (SQLite)
    runs-on: ubuntu-latest
    env:
      APP_ENV: dev
      APP_SECRET: KnR9FtX39zUT7Um8873wG2Rqv9nU7nve
      TRUSTED_PROXIES: 127.0.0.0/8
      TRUSTED_HOSTS: ^localhost$
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/bolt.sqlite
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$
    strategy:
      fail-fast: true
      matrix:
        php-versions:
          - '7.4'
        tools:
          - 'composer:2'
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, extensions and composer with shivammathur/setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl, zip, gd, exif, pdo, iconv, pcntl, mbstring, fileinfo, posix
        tools: ${{ matrix.tools }}
      env:
        update: true
    - name: Install Symfony Flex
      run: |
        composer global config --no-plugins allow-plugins.symfony/flex true
        composer global require --prefer-dist --no-progress --ansi symfony/flex
    - name: Install project with composer
      run: |
        composer install --prefer-dist --no-progress --no-interaction
        composer clear-cache
    - name: Setup up Bolt project
      run: |
        php bin/console doctrine:schema:create --env dev
        php bin/console doctrine:fixtures:load --group=without-images --no-interaction
        composer run post-create-project-cmd
        php bin/console bolt:info
    - name: Check HTTP reachability
      run: |
        wget https://get.symfony.com/cli/installer -O - | bash
        /home/runner/.symfony5/bin/symfony serve --daemon --no-tls
        echo "Check => http://localhost:8000" && curl -fkI http://localhost:8000
        echo "Check => http://localhost:8000/bolt" && curl -fkI http://localhost:8000/bolt
    - name: Validate composer.json
      run: composer validate --no-check-publish
    - name: Run PHP-CS-Fixer
      run: composer lint
    - name: Run PHP-CS-Fixer with fix flag
      run: composer lint:fix
    - name: Run PHPStan
      run: composer phpstan

  test-install-with-composer-and-mysql:
    name: Install Bolt project with Composer (MySQL 5.7)
    runs-on: ubuntu-latest
    env:
      APP_ENV: dev
      APP_SECRET: KnR9FtX39zUT7Um8873wG2Rqv9nU7nve
      TRUSTED_PROXIES: 127.0.0.0/8
      TRUSTED_HOSTS: ^localhost$
      DATABASE_URL: mysql://bolt:Q2ttiAeS6DT329c9@127.0.0.1:3306/bolt?serverVersion=5.7
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: bolt
          MYSQL_PASSWORD: Q2ttiAeS6DT329c9
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_USER: bolt
        ports:
        - 3306:3306
        options: >-
          --mount type=tmpfs,destination=/var/lib/mysql
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: true
      matrix:
        php-versions:
          - '7.4'
        tools:
          - 'composer:2'
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, extensions and composer with shivammathur/setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl, pdo_mysql, zip, gd, exif, pdo, iconv, pcntl, mbstring, fileinfo, posix
        tools: ${{ matrix.tools }}
      env:
        update: true
    - name: Install Symfony Flex
      run: |
        composer global config --no-plugins allow-plugins.symfony/flex true
        composer global require --prefer-dist --no-progress --ansi symfony/flex
    - name: Install project with composer
      run: |
        composer install --prefer-dist --no-progress --no-interaction
        composer clear-cache
    - name: Verify MySQL connection from host
      run: php bin/console doctrine:query:sql "SELECT 1" > /dev/null 2>&1
    - name: Setup up Bolt project
      run: |
        php bin/console doctrine:schema:create --env dev
        php bin/console doctrine:fixtures:load --group=without-images --no-interaction
        composer run post-create-project-cmd
        php bin/console bolt:info
    - name: Check HTTP reachability
      run: |
        wget https://get.symfony.com/cli/installer -O - | bash
        /home/runner/.symfony5/bin/symfony serve --daemon --no-tls
        echo "Check => http://localhost:8000" && curl -fkI http://localhost:8000
        echo "Check => http://localhost:8000/bolt" && curl -fkI http://localhost:8000/bolt
    - name: Validate composer.json
      run: composer validate --no-check-publish
    - name: Run PHP-CS-Fixer
      run: composer lint
    - name: Run PHP-CS-Fixer with fix flag
      run: composer lint:fix
    - name: Run PHPStan
      run: composer phpstan
